controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

view-recipe: 
    path: /view-recipe
    controller: App\Controller\ViewRecipeController::index
    

maquinaria_edit:
    path: /maquinaria/{id}/edit
    controller: App\Controller\MaquinariaController::edit
    methods: [GET, POST]
